/**
 * SHAPE REGISTRY
 * ==============
 * The single place where every custom game shape is collected and handed to
 * tldraw. To add a new shape you do NOT edit this file's logic — you import your
 * ShapeUtil (and optional Tool) and drop it into the arrays below.
 *
 * Pattern (see CLAUDE.md → "Adding a shape"):
 *   1. Create `client/shapes/<YourShape>.tsx` exporting a `<Your>ShapeUtil` class.
 *   2. (optional) Create `client/tools/<YourShape>Tool.ts` exporting a `StateNode`.
 *   3. Add both to the arrays in this file.
 *
 * Everything else (registration with <Tldraw>, the toolbar button, the menu)
 * reads from these arrays, so this is the only wiring you touch.
 */
import {
	TLAnyBindingUtilConstructor,
	TLAnyShapeUtilConstructor,
	TLStateNodeConstructor,
	defaultBindingUtils,
	defaultShapeUtils,
} from 'tldraw'
import { ContainmentBindingUtil } from '../containment/ContainmentBinding'
import { BloomShapeUtil } from './BloomShape'
import { CardShapeUtil } from './CardShape'
import { ContainerShapeUtil } from './ContainerShape'
import { FrondShapeUtil } from './FrondShape'
import { HydraShapeUtil } from './HydraShape'
import { PlumeShapeUtil } from './PlumeShape'
import { RibbonShapeUtil } from './RibbonShape'
import { SpiderShapeUtil } from './SpiderShape'
import { SpiderBlobsShapeUtil } from './SpiderBlobsShape'
import { SpiderOvalShapeUtil } from './SpiderOvalShape'
import { CreatureShapeUtil } from './CreatureShape'
import { DieShapeUtil } from './DieShape'
import { GridShapeUtil } from './GridShape'
import { TokenShapeUtil } from './TokenShape'
import { TrackerShapeUtil } from './TrackerShape'

/**
 * All shape utils registered with the editor via `<Tldraw shapeUtils={...}>` AND
 * the synced schema via `useSync({ shapeUtils })`.
 *
 * IMPORTANT: this MUST include tldraw's `defaultShapeUtils` (geo/draw/arrow/text/
 * note/…) because the SYNC SERVER registers `defaultShapeSchemas` too (see
 * worker/TldrawDurableObject.ts). If the client omitted the defaults, the two
 * schemas would diverge and every client would be rejected at the sync handshake
 * with CLIENT_TOO_OLD. Keep the two sides in lockstep.
 *
 * Order does not matter. Add your custom `<Your>ShapeUtil` to the custom list.
 */
export const gameShapeUtils: TLAnyShapeUtilConstructor[] = [
	...defaultShapeUtils,
	TokenShapeUtil,
	TrackerShapeUtil,
	DieShapeUtil,
	CardShapeUtil,
	ContainerShapeUtil,
	GridShapeUtil,
	CreatureShapeUtil,
	BloomShapeUtil,
	HydraShapeUtil,
	FrondShapeUtil,
	PlumeShapeUtil,
	RibbonShapeUtil,
	SpiderShapeUtil,
	SpiderBlobsShapeUtil,
	SpiderOvalShapeUtil,
	// ← add your `<Your>ShapeUtil` here
]

/**
 * Custom bindings (relationships between shapes). The containment binding links
 * a Container to the pieces inside it. Registered with `<Tldraw bindingUtils>`
 * and the synced schema, same as shapes.
 */
export const gameBindingUtils: TLAnyBindingUtilConstructor[] = [
	...defaultBindingUtils,
	ContainmentBindingUtil,
	// ← add your `<Your>BindingUtil` here
]

/**
 * Custom tools (the things you click in the toolbar to place a shape).
 * Each entry pairs with a toolbar button defined in `client/ui/components.tsx`.
 * A shape that is only ever created programmatically (not placed by hand) does
 * not need a tool here.
 */
export const gameTools: TLStateNodeConstructor[] = [
	// ← add your `<Your>Tool` here (import from ../tools/)
]
