/**
 * SHAPE REGISTRY
 * ==============
 * The single place where every custom game shape is collected and handed to
 * tldraw. To add a new shape you do NOT edit this file's logic — you import your
 * ShapeUtil (and optional Tool) and drop it into the arrays below.
 *
 * Pattern (see CLAUDE.md → "Adding a shape"):
 *   1. Create `client/shapes/<YourShape>.tsx` exporting a `<Your>ShapeUtil` class.
 *   2. (optional) Create `client/tools/<YourShape>Tool.ts` exporting a `StateNode`.
 *   3. Add both to the arrays in this file.
 *
 * Everything else (registration with <Tldraw>, the toolbar button, the menu)
 * reads from these arrays, so this is the only wiring you touch.
 */
import { TLAnyShapeUtilConstructor, TLStateNodeConstructor } from 'tldraw'
import { DieShapeUtil } from './DieShape'
import { TokenShapeUtil } from './TokenShape'
import { TrackerShapeUtil } from './TrackerShape'

/**
 * All custom game-shape utils, registered with the editor via `<Tldraw shapeUtils={...}>`.
 * Order does not matter.
 */
export const gameShapeUtils: TLAnyShapeUtilConstructor[] = [
	TokenShapeUtil,
	TrackerShapeUtil,
	DieShapeUtil,
	// ← add your `<Your>ShapeUtil` here
]

/**
 * Custom tools (the things you click in the toolbar to place a shape).
 * Each entry pairs with a toolbar button defined in `client/ui/components.tsx`.
 * A shape that is only ever created programmatically (not placed by hand) does
 * not need a tool here.
 */
export const gameTools: TLStateNodeConstructor[] = [
	// ← add your `<Your>Tool` here (import from ../tools/)
]
